### ISSUE TITLE
Where is the mod?

### ISSUE THREAD

**Issue by Zilarrezko** [stonehearth/startermod_basic#1]
Sorry if I missed some detail... But was there suppose to be a reference mod here? Or is this just a placeholder for later when it's finished? Sorry to be a naggy neil / bossy berry / whatever alliteration combination of an adjective and a name.

**Comment by sylestra** [comment]
It's a placeholder. I'll put it up when there's a lull in A11 bugfixing.

**Comment by Zilarrezko** [comment]
ah! okay cool, closing issue now.

**Comment by sylestra** [comment]
Annnd... now it's up! :D Thanks for the extra motivation.

**Comment by Xynariz** [comment]
Yay!  Just one day after I started working on my fist mod... Thanks @sylestra (or sdee, or Stephanie).

**Comment by sylestra** [comment]
My pleasure! Let me know what else you guys would like to see in the startermod. (Or other, similar mods. :))
